[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_port = /dev/cu.usbserial-110
upload_port = /dev/cu.usbserial-110
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^7.1.0
    ESP32Async/AsyncTCP @ ^3.3.2
    ESP32Async/ESPAsyncWebServer @ ^3.6.0
    majicdesigns/MD_MAX72XX @ ^3.3.1
